#!/usr/bin/env bash

# Removes all generated makefiles
make -f Makefile clean-make

# Dependencies for local or global builds.
# When building the packages separately, dependencies are not set as everything
# should already be available in $(COQMF_LIB)/user-contrib/TypedExtraction/*
# For local builds, we set specific dependencies of each subproject in */_config

if command -v rocq >/dev/null 2>&1
then
    if [[ "$1" = "local" ]] || [[ "$1" = "--enable-local" ]]
    then
        echo "Building TypedExtraction locally"
        COMMON_DEP="-Q ../common/theories TypedExtraction.Common"
        ELM_DEP="-Q ../elm/theories TypedExtraction.Elm"
        RUST_DEP="-Q ../rust/theories TypedExtraction.Rust"
        PLUGIN_DEP="-Q ../plugin/theories TypedExtraction.Plugin -I ../plugin/src"
    else
        echo "Building TypedExtraction globally (default)"
        COMMON_DEP=""
        ELM_DEP=""
        RUST_DEP=""
        PLUGIN_DEP=""
    fi

    echo "# DO NOT EDIT THIS FILE: autogenerated from ./configure.sh" > elm/_config
    echo "# DO NOT EDIT THIS FILE: autogenerated from ./configure.sh" > rust/_config
    echo "# DO NOT EDIT THIS FILE: autogenerated from ./configure.sh" > plugin/_config
    echo "# DO NOT EDIT THIS FILE: autogenerated from ./configure.sh" > tests/_config

    echo ${COMMON_DEP} >> elm/_config
    echo ${COMMON_DEP} >> rust/_config
    echo ${COMMON_DEP} ${ELM_DEP} ${RUST_DEP} >> plugin/_config
    echo ${COMMON_DEP} ${ELM_DEP} ${RUST_DEP} ${PLUGIN_DEP} >> tests/_config
else
    echo "Error: rocq not found in path"
fi
